# Generated by Django 5.1 on 2024-10-07 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bankcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('receiver_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='main.bankaccount')),
                ('sender_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='main.bankcard')),
            ],
        ),
    ]
